### ISSUE TITLE
Add more resources and instruction on readme,md

### ISSUE THREAD

**Issue by vidhyav656** [vidhyav656/Learning-git#1]
1. Basic system requirement for mac, windows, Linux os
2. Add installation instructions

**Comment by Akhil-chaudhary** [comment]
Assign me this issue, I will update the readme.md with instructions.

**Comment by vidhyav656** [comment]
@Akhil-chaudhary  great.  Thank you in advance.

**Comment by vidhyav656** [comment]
#2
