### ISSUE TITLE
Add License for the repo

### ISSUE THREAD

**Issue by vidhyav656** [vidhyav656/Learning-git#9]

**Comment by zmusaddique** [comment]
Hi @vidhyav656!

I would like to work on this

**Comment by zmusaddique** [comment]
Which license do you prefer? Apache 2.0 (or) GNU v3.0 (or) MIT LICENSE
MIT LICENSE is commonly used

**Comment by vidhyav656** [comment]
I will go with MIT License.

**Comment by zmusaddique** [comment]
Ok!

**Comment by vidhyav656** [comment]
closes #17
